# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 00:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(max_length=1)),
                ('comment', models.CharField(max_length=800)),
                ('skills', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cid', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('start', models.CharField(max_length=5)),
                ('end', models.CharField(max_length=5)),
                ('days', models.CharField(max_length=15)),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csvfile', models.FileField(null=True, upload_to='cmucoursebook/static')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=6)),
                ('year', models.CharField(max_length=4)),
                ('instructor', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('cid', models.CharField(max_length=5)),
                ('coursename', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=3)),
                ('ctype', models.CharField(max_length=5)),
                ('response', models.CharField(max_length=3)),
                ('enrollment', models.CharField(max_length=3)),
                ('resprate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('iisl', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ecr', models.DecimalField(decimal_places=2, max_digits=3)),
                ('clg', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ipfs', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ios', models.DecimalField(decimal_places=2, max_digits=3)),
                ('esm', models.DecimalField(decimal_places=2, max_digits=3)),
                ('srs', models.DecimalField(decimal_places=2, max_digits=3)),
                ('os', models.DecimalField(decimal_places=2, max_digits=3)),
                ('oc', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('from_city', models.CharField(blank=True, max_length=50, null=True)),
                ('from_country', models.CharField(blank=True, max_length=50, null=True)),
                ('bio', models.CharField(blank=True, max_length=430, null=True)),
                ('img', models.FileField(null=True, upload_to='cmucoursebook/static')),
                ('pending', models.IntegerField(default=0)),
                ('curr', models.ManyToManyField(related_name='current_courses', to='cmucoursebook.Course')),
                ('friends', models.ManyToManyField(related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('liked', models.ManyToManyField(related_name='liked_courses', to='cmucoursebook.Course')),
                ('past', models.ManyToManyField(related_name='past_courses', to='cmucoursebook.Course')),
                ('pending_friends', models.ManyToManyField(related_name='pending_friends', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ManyToManyField(related_name='planned_courses', to='cmucoursebook.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_course', to='cmucoursebook.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_course', to='cmucoursebook.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
                ('start', models.CharField(blank=True, max_length=5, null=True)),
                ('end', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='timeslot',
            field=models.ManyToManyField(related_name='schedule_time', to='cmucoursebook.Timeslot'),
        ),
        migrations.AddField(
            model_name='comment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_course', to='cmucoursebook.Course'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
